### PR TITLE
Generate User, Post and Comment models

### PR DESCRIPTION
**Pull request by anewman15**
In this PR,

I used Active Record to generate User, Post and Comment models by applying migration, validation and association concepts. All the data was created from the rails console.

### CODE REVIEW

**Review by adaorachi — CHANGES_REQUESTED** [review]
### Hi @anewman15 :wave: 
You've done a good job on this project. The models are well created and their associations are well implemented too. Well done!
However, there are a couple of changes to implement in order to get your project approved.

---

### STATUS: CHANGES REQUIRED :recycle: 

---

- [ ]  Kindly ensure that GitHub action linter files are properly set for your repo. There should be an indication of the flagged error messages or an `All checks have passed` messages in this Pull Request. Kindly follow the guidelines [here](https://github.com/microverseinc/linters-config/tree/master/ror) and also ensure that Github action is enabled in the actions tab of this repo.

- [ ] In your README, Kindly remove the default content and update its contents to reflect the features you implemented in this project. It should have a detailed project description, how to set-up and use your project, and other necessary info that are required in a descriptive README.

- [ ] Kindly improve on your commit messages in subsequent commits. You should commit as often as possible, preferably after you have completed a feature or a unit of work. This helps to make your repo look more professional and easy to revert your changes if you encounter any issues. For example - this commit `Create Post model, add migration, validation and associations` should have been broken down into units like so - `create post model and migrate to database`, `add validations for post model` and, `create associations for post and user models`.

- [**optional**]  It will be nice if you add a post_body attribute to your post model. It is typical that a post should have at least a title and a body.

---
### After implementing the mandatory changes, you can request for another code review
#### Note: All requirements not marked with OPTIONAL are considered mandatory.
 
---

Should you have any question, kindly reach out to me on Slack with the username @adaorachi

Happy Coding :relaxed: 

MaryAnn Chukwuka.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Abdullah Numan** 
Great job with the improvements to your project :muscle:  :muscle: 
We still need to fix some details:
- [ ] Your Post model should have a body attribute which refers to the content of the post
- [x] In your User model, remove the limit of 15 characters to the username
- [ ] In your User model, add a validation to only accept valid emails (use regex)
- [x] In your README file, deployment section, it's necessary that user run 'rails db:migrate'

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by anewman15** [comment]
@andresporras3423 
I've picked "one" detail to fix: removed the 15 character max limit from User
- As a bonus, I added the `rails db:migrate` command just because you also didn't add that in your own project. Please add that in your readme.

Didn't choose the rest because,
- Last time I checked reddit.com, posts don't have a body. Just the title (which happens to be the url to start with).
- Regex validation was not part of the material, so I'll leave it for later.

**Review by maelfosso — APPROVED** [review]
# Congratulations :red_circle: 

Thank you for applying the suggested changes 
You did a good job and you can merge :+1: 

Good continuation :handshake: 

Mael FOSSO

**Pull request merged**
